apiVersion: v2
name: customer-portal-ui
type: application
version: 0.0.1
appVersion: 0.0.1
description: "Labs64.IO :: Customer Portal UI â€“ Frontend Interface for the Labs64 Customer Portal, built with Vite and Vue 3."
icon: https://raw.githubusercontent.com/Labs64/.github/refs/heads/master/assets/labs64-avatar-128x128.png
home: https://labs64.io
keywords:
  - labs64io
  - ecosystem
  - customer-portal
  - frontend
  - vue
sources:
  - https://github.com/Labs64/labs64.io-helm-charts
  - https://github.com/Labs64/labs64.io-customer-portal
maintainers:
  - name: labs64
    email: info@labs64.com
dependencies:
  - name: chart-libs
    version: 0.0.1
    repository: file://../chart-libs

