image:
  repository: localhost:5005/traefik-authproxy
  tag: latest

env:
  - name: OIDC_DISCOVERY_URL
    value: http://keycloak.tools.svc.cluster.local/realms/labs64io/.well-known/openid-configuration
  - name: OIDC_AUDIENCE
    value: account
  - name: ROLE_MAPPING_FILE
    value: /opt/application-config/role_mapping.yaml
  - name: LOG_LEVEL
    value: DEBUG

roleMapping:
  /auditflow/v3/api-docs: []
  /checkout/v3/api-docs: []

  /api/v1/admin:
    - admin-role
  /api/v1/auditflow:
    - admin-role
    - auditflow-role
    - default-roles-labs64io
  /api/v1/checkout:
    - admin-role
    - ecommerce-role
    - default-roles-labs64io
