{{- if .Values.ingressroute.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "chart-libs.fullname" . }}
spec:
  entryPoints:
    {{- toYaml .Values.ingressroute.entryPoints | nindent 4 }}
  routes:
    - match: Host(`{{ include "chart-libs.fullname" . }}.{{ .Values.ingressroute.host }}`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: {{ include "chart-libs.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}

