apiVersion: v2
name: payment-gateway
type: application
version: 0.0.1
appVersion: 0.0.1
description: "Labs64.IO :: Payment Gateway - Universal Payment Gateway for PSP Integration"
icon: https://raw.githubusercontent.com/Labs64/.github/refs/heads/master/assets/labs64-avatar-128x128.png
home: https://labs64.io
keywords:
  - labs64io
  - ecosystem
  - ecommerce
  - payment
  - gateway
  - psp
  - stripe
  - paypal
sources:
  - https://github.com/Labs64/labs64.io-helm-charts
  - https://github.com/Labs64/labs64.io-payment-gateway
maintainers:
  - name: labs64
    email: info@labs64.com
dependencies:
  - name: chart-libs
    version: 0.0.1
    repository: file://../chart-libs

