{{- if .Values.secrets.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart-libs.fullname" . }}
  labels:
    {{- include "chart-libs.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
